# -*- coding: utf-8 -*-
"""vehicle_fuel_efficency_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vlnnjFES1PZvBgcMvnSrhDozemUdOAu
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("vehicle_fuel_efficency_model (1).pkl")
encoder = joblib.load("label_encoder (1).pkl")

st.title("vehicle fuel efficency app")

engine_size = st.number_input("Engine Size", min_value=0.0, step=0.1)
cylinders = st.number_input("Cylinders", min_value=1, step=1)
transmission = st.selectbox("Transmission", ["Automatic", "Manual"])
fuel_type = st.selectbox("Fuel Type", ["Petrol", "Diesel", "CNG", "Electric"])
vehicle_class = st.selectbox("Vehicle Class", ["SUV", "Sedan", "Hatchback", "Truck"])


input_df = pd.DataFrame({
    "engine_size": [engine_size],
    "cylinders": [cylinders],
    "transmission": [transmission],
    "fuel_type": [fuel_type],
    "vehicle_class": [vehicle_class]
})


for col in encoders:
    input_df[col] = encoders[col].transform(input_df[col])

if st.button("Predict Fuel Efficiency"):
    prediction = model.predict(input_df)
    st.success(f"Predicted Fuel Efficiency: {prediction[0]:.2f}")





